// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ActionsSecretInitParameters struct {

	// Name of the repository.
	Repository *string `json:"repository,omitempty" tf:"repository,omitempty"`

	// Owner of the repository.
	RepositoryOwner *string `json:"repositoryOwner,omitempty" tf:"repository_owner,omitempty"`

	// Name of the secret.
	SecretName *string `json:"secretName,omitempty" tf:"secret_name,omitempty"`

	// Value of the secret.
	SecretValueSecretRef v1.LocalSecretKeySelector `json:"secretValueSecretRef" tf:"-"`
}

type ActionsSecretObservation struct {

	// Date of 'actions_secret' creation.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Name of the repository.
	Repository *string `json:"repository,omitempty" tf:"repository,omitempty"`

	// Owner of the repository.
	RepositoryOwner *string `json:"repositoryOwner,omitempty" tf:"repository_owner,omitempty"`

	// Name of the secret.
	SecretName *string `json:"secretName,omitempty" tf:"secret_name,omitempty"`
}

type ActionsSecretParameters struct {

	// Name of the repository.
	// +kubebuilder:validation:Optional
	Repository *string `json:"repository,omitempty" tf:"repository,omitempty"`

	// Owner of the repository.
	// +kubebuilder:validation:Optional
	RepositoryOwner *string `json:"repositoryOwner,omitempty" tf:"repository_owner,omitempty"`

	// Name of the secret.
	// +kubebuilder:validation:Optional
	SecretName *string `json:"secretName,omitempty" tf:"secret_name,omitempty"`

	// Value of the secret.
	// +kubebuilder:validation:Optional
	SecretValueSecretRef v1.LocalSecretKeySelector `json:"secretValueSecretRef" tf:"-"`
}

// ActionsSecretSpec defines the desired state of ActionsSecret
type ActionsSecretSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ActionsSecretParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ActionsSecretInitParameters `json:"initProvider,omitempty"`
}

// ActionsSecretStatus defines the observed state of ActionsSecret.
type ActionsSecretStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ActionsSecretObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ActionsSecret is the Schema for the ActionsSecrets API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gitea}
type ActionsSecret struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.repository) || (has(self.initProvider) && has(self.initProvider.repository))",message="spec.forProvider.repository is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.repositoryOwner) || (has(self.initProvider) && has(self.initProvider.repositoryOwner))",message="spec.forProvider.repositoryOwner is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.secretName) || (has(self.initProvider) && has(self.initProvider.secretName))",message="spec.forProvider.secretName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.secretValueSecretRef)",message="spec.forProvider.secretValueSecretRef is a required parameter"
	Spec   ActionsSecretSpec   `json:"spec"`
	Status ActionsSecretStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ActionsSecretList contains a list of ActionsSecrets
type ActionsSecretList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ActionsSecret `json:"items"`
}

// Repository type metadata.
var (
	ActionsSecret_Kind             = "ActionsSecret"
	ActionsSecret_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ActionsSecret_Kind}.String()
	ActionsSecret_KindAPIVersion   = ActionsSecret_Kind + "." + CRDGroupVersion.String()
	ActionsSecret_GroupVersionKind = CRDGroupVersion.WithKind(ActionsSecret_Kind)
)

func init() {
	SchemeBuilder.Register(&ActionsSecret{}, &ActionsSecretList{})
}
