// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type KeyInitParameters struct {

	// (String) Armored SSH key to add
	// Armored SSH key to add
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (Boolean) Whether this key has read or read/write access
	// Whether this key has read or read/write access
	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`

	// (Number) The ID of the repository where the deploy key belongs to
	// The ID of the repository where the deploy key belongs to
	Repository *float64 `json:"repository,omitempty" tf:"repository,omitempty"`

	// (String) Name of the deploy key
	// Name of the deploy key
	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

type KeyObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Armored SSH key to add
	// Armored SSH key to add
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (Boolean) Whether this key has read or read/write access
	// Whether this key has read or read/write access
	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`

	// (Number) The ID of the repository where the deploy key belongs to
	// The ID of the repository where the deploy key belongs to
	Repository *float64 `json:"repository,omitempty" tf:"repository,omitempty"`

	// (String) Name of the deploy key
	// Name of the deploy key
	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

type KeyParameters struct {

	// (String) Armored SSH key to add
	// Armored SSH key to add
	// +kubebuilder:validation:Optional
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (Boolean) Whether this key has read or read/write access
	// Whether this key has read or read/write access
	// +kubebuilder:validation:Optional
	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`

	// (Number) The ID of the repository where the deploy key belongs to
	// The ID of the repository where the deploy key belongs to
	// +kubebuilder:validation:Optional
	Repository *float64 `json:"repository,omitempty" tf:"repository,omitempty"`

	// (String) Name of the deploy key
	// Name of the deploy key
	// +kubebuilder:validation:Optional
	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

// KeySpec defines the desired state of Key
type KeySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            KeyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider KeyInitParameters `json:"initProvider,omitempty"`
}

// KeyStatus defines the observed state of Key.
type KeyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        KeyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Key is the Schema for the Keys API. gitea_repository_key manages a deploy key for a single gitea_repository. Every key needs a unique name and unique key, i.e. no key can be added twice to the same repo
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gitea}
type Key struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.key) || (has(self.initProvider) && has(self.initProvider.key))",message="spec.forProvider.key is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.repository) || (has(self.initProvider) && has(self.initProvider.repository))",message="spec.forProvider.repository is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.title) || (has(self.initProvider) && has(self.initProvider.title))",message="spec.forProvider.title is a required parameter"
	Spec   KeySpec   `json:"spec"`
	Status KeyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// KeyList contains a list of Keys
type KeyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Key `json:"items"`
}

// Repository type metadata.
var (
	Key_Kind             = "Key"
	Key_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Key_Kind}.String()
	Key_KindAPIVersion   = Key_Kind + "." + CRDGroupVersion.String()
	Key_GroupVersionKind = CRDGroupVersion.WithKind(Key_Kind)
)

func init() {
	SchemeBuilder.Register(&Key{}, &KeyList{})
}
