// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type WebhookInitParameters struct {

	// Set webhook to active, e.g. `true`
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// Webhook authorization header
	AuthorizationHeader *string `json:"authorizationHeader,omitempty" tf:"authorization_header,omitempty"`

	// Set branch filter on the webhook, e.g. `"*"`
	BranchFilter *string `json:"branchFilter,omitempty" tf:"branch_filter,omitempty"`

	// The content type of the payload. It can be `json`, or `form`
	ContentType *string `json:"contentType,omitempty" tf:"content_type,omitempty"`

	// A list of events that will trigger the webhool, e.g. `["push"]`
	Events []*string `json:"events,omitempty" tf:"events,omitempty"`

	// Repository name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Webhook secret
	Secret *string `json:"secret,omitempty" tf:"secret,omitempty"`

	// Webhook type, e.g. `gitea`
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Target URL of the webhook
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// User name or organization name
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type WebhookObservation struct {

	// Set webhook to active, e.g. `true`
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// Webhook authorization header
	AuthorizationHeader *string `json:"authorizationHeader,omitempty" tf:"authorization_header,omitempty"`

	// Set branch filter on the webhook, e.g. `"*"`
	BranchFilter *string `json:"branchFilter,omitempty" tf:"branch_filter,omitempty"`

	// The content type of the payload. It can be `json`, or `form`
	ContentType *string `json:"contentType,omitempty" tf:"content_type,omitempty"`

	// Webhook creation timestamp
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// A list of events that will trigger the webhool, e.g. `["push"]`
	Events []*string `json:"events,omitempty" tf:"events,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Repository name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Webhook secret
	Secret *string `json:"secret,omitempty" tf:"secret,omitempty"`

	// Webhook type, e.g. `gitea`
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Target URL of the webhook
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// User name or organization name
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type WebhookParameters struct {

	// Set webhook to active, e.g. `true`
	// +kubebuilder:validation:Optional
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// Webhook authorization header
	// +kubebuilder:validation:Optional
	AuthorizationHeader *string `json:"authorizationHeader,omitempty" tf:"authorization_header,omitempty"`

	// Set branch filter on the webhook, e.g. `"*"`
	// +kubebuilder:validation:Optional
	BranchFilter *string `json:"branchFilter,omitempty" tf:"branch_filter,omitempty"`

	// The content type of the payload. It can be `json`, or `form`
	// +kubebuilder:validation:Optional
	ContentType *string `json:"contentType,omitempty" tf:"content_type,omitempty"`

	// A list of events that will trigger the webhool, e.g. `["push"]`
	// +kubebuilder:validation:Optional
	Events []*string `json:"events,omitempty" tf:"events,omitempty"`

	// Repository name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Webhook secret
	// +kubebuilder:validation:Optional
	Secret *string `json:"secret,omitempty" tf:"secret,omitempty"`

	// Webhook type, e.g. `gitea`
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Target URL of the webhook
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// User name or organization name
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

// WebhookSpec defines the desired state of Webhook
type WebhookSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            WebhookParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider WebhookInitParameters `json:"initProvider,omitempty"`
}

// WebhookStatus defines the observed state of Webhook.
type WebhookStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        WebhookObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Webhook is the Schema for the Webhooks API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gitea}
type Webhook struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.active) || (has(self.initProvider) && has(self.initProvider.active))",message="spec.forProvider.active is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.branchFilter) || (has(self.initProvider) && has(self.initProvider.branchFilter))",message="spec.forProvider.branchFilter is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.contentType) || (has(self.initProvider) && has(self.initProvider.contentType))",message="spec.forProvider.contentType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.events) || (has(self.initProvider) && has(self.initProvider.events))",message="spec.forProvider.events is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.url) || (has(self.initProvider) && has(self.initProvider.url))",message="spec.forProvider.url is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.username) || (has(self.initProvider) && has(self.initProvider.username))",message="spec.forProvider.username is a required parameter"
	Spec   WebhookSpec   `json:"spec"`
	Status WebhookStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WebhookList contains a list of Webhooks
type WebhookList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Webhook `json:"items"`
}

// Repository type metadata.
var (
	Webhook_Kind             = "Webhook"
	Webhook_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Webhook_Kind}.String()
	Webhook_KindAPIVersion   = Webhook_Kind + "." + CRDGroupVersion.String()
	Webhook_GroupVersionKind = CRDGroupVersion.WithKind(Webhook_Kind)
)

func init() {
	SchemeBuilder.Register(&Webhook{}, &WebhookList{})
}
