// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// This file registers controllers that are hand-written rather than
// generated by upjet. Keeping them out of zz_setup.go avoids them being
// dropped on regeneration.

package controller

import (
	ctrl "sigs.k8s.io/controller-runtime"

	"github.com/crossplane/upjet/v2/pkg/controller"

	orgactionssecret "github.com/0xayf/provider-upjet-gitea/internal/controller/namespaced/repository/orgactionssecret"
	useractionssecret "github.com/0xayf/provider-upjet-gitea/internal/controller/namespaced/repository/useractionssecret"
)

// SetupCustom registers hand-written namespaced controllers.
func SetupCustom(mgr ctrl.Manager, o controller.Options) error {
	for _, setup := range []func(ctrl.Manager, controller.Options) error{
		orgactionssecret.Setup,
		useractionssecret.Setup,
	} {
		if err := setup(mgr, o); err != nil {
			return err
		}
	}
	return nil
}

// SetupCustomGated registers hand-written namespaced controllers gated.
func SetupCustomGated(mgr ctrl.Manager, o controller.Options) error {
	for _, setup := range []func(ctrl.Manager, controller.Options) error{
		orgactionssecret.SetupGated,
		useractionssecret.SetupGated,
	} {
		if err := setup(mgr, o); err != nil {
			return err
		}
	}
	return nil
}
