// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ForkInitParameters struct {

	// (String) The organization that owns the forked repo
	// The organization that owns the forked repo
	Organization *string `json:"organization,omitempty" tf:"organization,omitempty"`

	// (String) The owner or owning organization of the repository to fork
	// The owner or owning organization of the repository to fork
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// (String) The name of the repository to fork
	// The name of the repository to fork
	Repo *string `json:"repo,omitempty" tf:"repo,omitempty"`
}

type ForkObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The organization that owns the forked repo
	// The organization that owns the forked repo
	Organization *string `json:"organization,omitempty" tf:"organization,omitempty"`

	// (String) The owner or owning organization of the repository to fork
	// The owner or owning organization of the repository to fork
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// (String) The name of the repository to fork
	// The name of the repository to fork
	Repo *string `json:"repo,omitempty" tf:"repo,omitempty"`
}

type ForkParameters struct {

	// (String) The organization that owns the forked repo
	// The organization that owns the forked repo
	// +kubebuilder:validation:Optional
	Organization *string `json:"organization,omitempty" tf:"organization,omitempty"`

	// (String) The owner or owning organization of the repository to fork
	// The owner or owning organization of the repository to fork
	// +kubebuilder:validation:Optional
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// (String) The name of the repository to fork
	// The name of the repository to fork
	// +kubebuilder:validation:Optional
	Repo *string `json:"repo,omitempty" tf:"repo,omitempty"`
}

// ForkSpec defines the desired state of Fork
type ForkSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ForkParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ForkInitParameters `json:"initProvider,omitempty"`
}

// ForkStatus defines the observed state of Fork.
type ForkStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ForkObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Fork is the Schema for the Forks API. gitea_fork manages repository fork to the current user or an organisation Forking a repository to a dedicated user is currently unsupported Creating a fork using this resource without an organisation will create the fork in the executors name
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gitea}
type Fork struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.owner) || (has(self.initProvider) && has(self.initProvider.owner))",message="spec.forProvider.owner is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.repo) || (has(self.initProvider) && has(self.initProvider.repo))",message="spec.forProvider.repo is a required parameter"
	Spec   ForkSpec   `json:"spec"`
	Status ForkStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ForkList contains a list of Forks
type ForkList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Fork `json:"items"`
}

// Repository type metadata.
var (
	Fork_Kind             = "Fork"
	Fork_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Fork_Kind}.String()
	Fork_KindAPIVersion   = Fork_Kind + "." + CRDGroupVersion.String()
	Fork_GroupVersionKind = CRDGroupVersion.WithKind(Fork_Kind)
)

func init() {
	SchemeBuilder.Register(&Fork{}, &ForkList{})
}
