// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type OrgInitParameters struct {

	// (String) A description of this organisation.
	// A description of this organisation.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The display name of the organisation. Defaults to the value of name.
	// The display name of the organisation. Defaults to the value of `name`.
	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	// (String)
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) The name of the organisation without spaces.
	// The name of the organisation without spaces.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean)
	RepoAdminChangeTeamAccess *bool `json:"repoAdminChangeTeamAccess,omitempty" tf:"repo_admin_change_team_access,omitempty"`

	// (String) Flag is this organisation should be publicly visible or not.
	// Flag is this organisation should be publicly visible or not.
	Visibility *string `json:"visibility,omitempty" tf:"visibility,omitempty"`

	// (String) A link to a website with more information about this organisation.
	// A link to a website with more information about this organisation.
	Website *string `json:"website,omitempty" tf:"website,omitempty"`
}

type OrgObservation struct {

	// (String)
	AvatarURL *string `json:"avatarUrl,omitempty" tf:"avatar_url,omitempty"`

	// (String) A description of this organisation.
	// A description of this organisation.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The display name of the organisation. Defaults to the value of name.
	// The display name of the organisation. Defaults to the value of `name`.
	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) The name of the organisation without spaces.
	// The name of the organisation without spaces.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean)
	RepoAdminChangeTeamAccess *bool `json:"repoAdminChangeTeamAccess,omitempty" tf:"repo_admin_change_team_access,omitempty"`

	// (List of String) List of all Repositories that are part of this organisation
	// List of all Repositories that are part of this organisation
	Repos []*string `json:"repos,omitempty" tf:"repos,omitempty"`

	// (String) Flag is this organisation should be publicly visible or not.
	// Flag is this organisation should be publicly visible or not.
	Visibility *string `json:"visibility,omitempty" tf:"visibility,omitempty"`

	// (String) A link to a website with more information about this organisation.
	// A link to a website with more information about this organisation.
	Website *string `json:"website,omitempty" tf:"website,omitempty"`
}

type OrgParameters struct {

	// (String) A description of this organisation.
	// A description of this organisation.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The display name of the organisation. Defaults to the value of name.
	// The display name of the organisation. Defaults to the value of `name`.
	// +kubebuilder:validation:Optional
	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) The name of the organisation without spaces.
	// The name of the organisation without spaces.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	RepoAdminChangeTeamAccess *bool `json:"repoAdminChangeTeamAccess,omitempty" tf:"repo_admin_change_team_access,omitempty"`

	// (String) Flag is this organisation should be publicly visible or not.
	// Flag is this organisation should be publicly visible or not.
	// +kubebuilder:validation:Optional
	Visibility *string `json:"visibility,omitempty" tf:"visibility,omitempty"`

	// (String) A link to a website with more information about this organisation.
	// A link to a website with more information about this organisation.
	// +kubebuilder:validation:Optional
	Website *string `json:"website,omitempty" tf:"website,omitempty"`
}

// OrgSpec defines the desired state of Org
type OrgSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            OrgParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OrgInitParameters `json:"initProvider,omitempty"`
}

// OrgStatus defines the observed state of Org.
type OrgStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        OrgObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Org is the Schema for the Orgs API. gitea_org manages a gitea organisation. Organisations are a way to group repositories and abstract permission management in a gitea instance.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gitea}
type Org struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   OrgSpec   `json:"spec"`
	Status OrgStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OrgList contains a list of Orgs
type OrgList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Org `json:"items"`
}

// Repository type metadata.
var (
	Org_Kind             = "Org"
	Org_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Org_Kind}.String()
	Org_KindAPIVersion   = Org_Kind + "." + CRDGroupVersion.String()
	Org_GroupVersionKind = CRDGroupVersion.WithKind(Org_Kind)
)

func init() {
	SchemeBuilder.Register(&Org{}, &OrgList{})
}
