// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type RepositoryInitParameters struct {

	// (Boolean)
	AllowManualMerge *bool `json:"allowManualMerge,omitempty" tf:"allow_manual_merge,omitempty"`

	// (Boolean)
	AllowMergeCommits *bool `json:"allowMergeCommits,omitempty" tf:"allow_merge_commits,omitempty"`

	// (Boolean)
	AllowRebase *bool `json:"allowRebase,omitempty" tf:"allow_rebase,omitempty"`

	// (Boolean)
	AllowRebaseExplicit *bool `json:"allowRebaseExplicit,omitempty" tf:"allow_rebase_explicit,omitempty"`

	// (Boolean)
	AllowSquashMerge *bool `json:"allowSquashMerge,omitempty" tf:"allow_squash_merge,omitempty"`

	// (Boolean) Set to 'true' to archive the repository instead of deleting on destroy.
	// Set to 'true' to archive the repository instead of deleting on destroy.
	ArchiveOnDestroy *bool `json:"archiveOnDestroy,omitempty" tf:"archive_on_destroy,omitempty"`

	// (Boolean)
	Archived *bool `json:"archived,omitempty" tf:"archived,omitempty"`

	// (Boolean) Flag if the repository should be initiated with the configured values
	// Flag if the repository should be initiated with the configured values
	AutoInit *bool `json:"autoInit,omitempty" tf:"auto_init,omitempty"`

	// (Boolean)
	AutodetectManualMerge *bool `json:"autodetectManualMerge,omitempty" tf:"autodetect_manual_merge,omitempty"`

	// (String) The default branch of the repository. Defaults to main
	// The default branch of the repository. Defaults to `main`
	DefaultBranch *string `json:"defaultBranch,omitempty" tf:"default_branch,omitempty"`

	// (String) The description of the repository.
	// The description of the repository.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) A specific gitignore that should be commited to the repositoryon creation if auto_init is set to true
	// Need to exist in the gitea instance
	// A specific gitignore that should be commited to the repositoryon creation if `auto_init` is set to `true`
	// Need to exist in the gitea instance
	Gitignores *string `json:"gitignores,omitempty" tf:"gitignores,omitempty"`

	// (Boolean) A flag if the repository should have issue management enabled or not.
	// A flag if the repository should have issue management enabled or not.
	HasIssues *bool `json:"hasIssues,omitempty" tf:"has_issues,omitempty"`

	// (Boolean) A flag if the repository should have the native project management enabled or not.
	// A flag if the repository should have the native project management enabled or not.
	HasProjects *bool `json:"hasProjects,omitempty" tf:"has_projects,omitempty"`

	// (Boolean) A flag if the repository should acceppt pull requests or not.
	// A flag if the repository should acceppt pull requests or not.
	HasPullRequests *bool `json:"hasPullRequests,omitempty" tf:"has_pull_requests,omitempty"`

	// (Boolean) A flag if the repository should have the native wiki enabled or not.
	// A flag if the repository should have the native wiki enabled or not.
	HasWiki *bool `json:"hasWiki,omitempty" tf:"has_wiki,omitempty"`

	// (Boolean)
	IgnoreWhitespaceConflicts *bool `json:"ignoreWhitespaceConflicts,omitempty" tf:"ignore_whitespace_conflicts,omitempty"`

	// (String) The Issue Label configuration to be used in this repository.
	// Need to exist in the gitea instance
	// The Issue Label configuration to be used in this repository.
	// Need to exist in the gitea instance
	IssueLabels *string `json:"issueLabels,omitempty" tf:"issue_labels,omitempty"`

	// (String) The license under which the source code of this repository should be.
	// Need to exist in the gitea instance
	// The license under which the source code of this repository should be.
	// Need to exist in the gitea instance
	License *string `json:"license,omitempty" tf:"license,omitempty"`

	// (String)
	MigrationCloneAddress *string `json:"migrationCloneAddress,omitempty" tf:"migration_clone_address,omitempty"`

	// (String) DEPRECATED in favor of migration_clone_address
	// DEPRECATED in favor of `migration_clone_address`
	MigrationCloneAddresse *string `json:"migrationCloneAddresse,omitempty" tf:"migration_clone_addresse,omitempty"`

	// (Boolean)
	MigrationIssueLabels *bool `json:"migrationIssueLabels,omitempty" tf:"migration_issue_labels,omitempty"`

	// (Boolean)
	MigrationLfs *bool `json:"migrationLfs,omitempty" tf:"migration_lfs,omitempty"`

	// (String)
	MigrationLfsEndpoint *string `json:"migrationLfsEndpoint,omitempty" tf:"migration_lfs_endpoint,omitempty"`

	// (Boolean)
	MigrationMilestones *bool `json:"migrationMilestones,omitempty" tf:"migration_milestones,omitempty"`

	// (String) valid time units are 'h', 'm', 's'. 0 to disable automatic sync
	// valid time units are 'h', 'm', 's'. 0 to disable automatic sync
	MigrationMirrorInterval *string `json:"migrationMirrorInterval,omitempty" tf:"migration_mirror_interval,omitempty"`

	// (Boolean)
	MigrationReleases *bool `json:"migrationReleases,omitempty" tf:"migration_releases,omitempty"`

	// (String) git/github/gitlab/gitea/gogs
	// git/github/gitlab/gitea/gogs
	MigrationService *string `json:"migrationService,omitempty" tf:"migration_service,omitempty"`

	// (String, Sensitive)
	MigrationServiceAuthPasswordSecretRef *v1.LocalSecretKeySelector `json:"migrationServiceAuthPasswordSecretRef,omitempty" tf:"-"`

	// (String, Sensitive)
	MigrationServiceAuthTokenSecretRef *v1.LocalSecretKeySelector `json:"migrationServiceAuthTokenSecretRef,omitempty" tf:"-"`

	// (String)
	MigrationServiceAuthUsername *string `json:"migrationServiceAuthUsername,omitempty" tf:"migration_service_auth_username,omitempty"`

	// (Boolean)
	Mirror *bool `json:"mirror,omitempty" tf:"mirror,omitempty"`

	// (String) The Name of the repository
	// The Name of the repository
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Flag if the repository should be private or not.
	// Flag if the repository should be private or not.
	Private *bool `json:"private,omitempty" tf:"private,omitempty"`

	// (String)
	Readme *string `json:"readme,omitempty" tf:"readme,omitempty"`

	// (Boolean)
	RepoTemplate *bool `json:"repoTemplate,omitempty" tf:"repo_template,omitempty"`

	// (String) The Owner of the repository
	// The Owner of the repository
	Username *string `json:"username,omitempty" tf:"username,omitempty"`

	// (String) A link to a website with more information.
	// A link to a website with more information.
	Website *string `json:"website,omitempty" tf:"website,omitempty"`
}

type RepositoryObservation struct {

	// (Boolean)
	AllowManualMerge *bool `json:"allowManualMerge,omitempty" tf:"allow_manual_merge,omitempty"`

	// (Boolean)
	AllowMergeCommits *bool `json:"allowMergeCommits,omitempty" tf:"allow_merge_commits,omitempty"`

	// (Boolean)
	AllowRebase *bool `json:"allowRebase,omitempty" tf:"allow_rebase,omitempty"`

	// (Boolean)
	AllowRebaseExplicit *bool `json:"allowRebaseExplicit,omitempty" tf:"allow_rebase_explicit,omitempty"`

	// (Boolean)
	AllowSquashMerge *bool `json:"allowSquashMerge,omitempty" tf:"allow_squash_merge,omitempty"`

	// (Boolean) Set to 'true' to archive the repository instead of deleting on destroy.
	// Set to 'true' to archive the repository instead of deleting on destroy.
	ArchiveOnDestroy *bool `json:"archiveOnDestroy,omitempty" tf:"archive_on_destroy,omitempty"`

	// (Boolean)
	Archived *bool `json:"archived,omitempty" tf:"archived,omitempty"`

	// (Boolean) Flag if the repository should be initiated with the configured values
	// Flag if the repository should be initiated with the configured values
	AutoInit *bool `json:"autoInit,omitempty" tf:"auto_init,omitempty"`

	// (Boolean)
	AutodetectManualMerge *bool `json:"autodetectManualMerge,omitempty" tf:"autodetect_manual_merge,omitempty"`

	// (String)
	CloneURL *string `json:"cloneUrl,omitempty" tf:"clone_url,omitempty"`

	// (String)
	Created *string `json:"created,omitempty" tf:"created,omitempty"`

	// (String) The default branch of the repository. Defaults to main
	// The default branch of the repository. Defaults to `main`
	DefaultBranch *string `json:"defaultBranch,omitempty" tf:"default_branch,omitempty"`

	// (String) The description of the repository.
	// The description of the repository.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) A specific gitignore that should be commited to the repositoryon creation if auto_init is set to true
	// Need to exist in the gitea instance
	// A specific gitignore that should be commited to the repositoryon creation if `auto_init` is set to `true`
	// Need to exist in the gitea instance
	Gitignores *string `json:"gitignores,omitempty" tf:"gitignores,omitempty"`

	// (String)
	HTMLURL *string `json:"htmlUrl,omitempty" tf:"html_url,omitempty"`

	// (Boolean) A flag if the repository should have issue management enabled or not.
	// A flag if the repository should have issue management enabled or not.
	HasIssues *bool `json:"hasIssues,omitempty" tf:"has_issues,omitempty"`

	// (Boolean) A flag if the repository should have the native project management enabled or not.
	// A flag if the repository should have the native project management enabled or not.
	HasProjects *bool `json:"hasProjects,omitempty" tf:"has_projects,omitempty"`

	// (Boolean) A flag if the repository should acceppt pull requests or not.
	// A flag if the repository should acceppt pull requests or not.
	HasPullRequests *bool `json:"hasPullRequests,omitempty" tf:"has_pull_requests,omitempty"`

	// (Boolean) A flag if the repository should have the native wiki enabled or not.
	// A flag if the repository should have the native wiki enabled or not.
	HasWiki *bool `json:"hasWiki,omitempty" tf:"has_wiki,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean)
	IgnoreWhitespaceConflicts *bool `json:"ignoreWhitespaceConflicts,omitempty" tf:"ignore_whitespace_conflicts,omitempty"`

	// (String) The Issue Label configuration to be used in this repository.
	// Need to exist in the gitea instance
	// The Issue Label configuration to be used in this repository.
	// Need to exist in the gitea instance
	IssueLabels *string `json:"issueLabels,omitempty" tf:"issue_labels,omitempty"`

	// (String) The license under which the source code of this repository should be.
	// Need to exist in the gitea instance
	// The license under which the source code of this repository should be.
	// Need to exist in the gitea instance
	License *string `json:"license,omitempty" tf:"license,omitempty"`

	// (String)
	MigrationCloneAddress *string `json:"migrationCloneAddress,omitempty" tf:"migration_clone_address,omitempty"`

	// (String) DEPRECATED in favor of migration_clone_address
	// DEPRECATED in favor of `migration_clone_address`
	MigrationCloneAddresse *string `json:"migrationCloneAddresse,omitempty" tf:"migration_clone_addresse,omitempty"`

	// (Boolean)
	MigrationIssueLabels *bool `json:"migrationIssueLabels,omitempty" tf:"migration_issue_labels,omitempty"`

	// (Boolean)
	MigrationLfs *bool `json:"migrationLfs,omitempty" tf:"migration_lfs,omitempty"`

	// (String)
	MigrationLfsEndpoint *string `json:"migrationLfsEndpoint,omitempty" tf:"migration_lfs_endpoint,omitempty"`

	// (Boolean)
	MigrationMilestones *bool `json:"migrationMilestones,omitempty" tf:"migration_milestones,omitempty"`

	// (String) valid time units are 'h', 'm', 's'. 0 to disable automatic sync
	// valid time units are 'h', 'm', 's'. 0 to disable automatic sync
	MigrationMirrorInterval *string `json:"migrationMirrorInterval,omitempty" tf:"migration_mirror_interval,omitempty"`

	// (Boolean)
	MigrationReleases *bool `json:"migrationReleases,omitempty" tf:"migration_releases,omitempty"`

	// (String) git/github/gitlab/gitea/gogs
	// git/github/gitlab/gitea/gogs
	MigrationService *string `json:"migrationService,omitempty" tf:"migration_service,omitempty"`

	// (String)
	MigrationServiceAuthUsername *string `json:"migrationServiceAuthUsername,omitempty" tf:"migration_service_auth_username,omitempty"`

	// (Boolean)
	Mirror *bool `json:"mirror,omitempty" tf:"mirror,omitempty"`

	// (String) The Name of the repository
	// The Name of the repository
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean)
	PermissionAdmin *bool `json:"permissionAdmin,omitempty" tf:"permission_admin,omitempty"`

	// (Boolean)
	PermissionPull *bool `json:"permissionPull,omitempty" tf:"permission_pull,omitempty"`

	// (Boolean)
	PermissionPush *bool `json:"permissionPush,omitempty" tf:"permission_push,omitempty"`

	// (Boolean) Flag if the repository should be private or not.
	// Flag if the repository should be private or not.
	Private *bool `json:"private,omitempty" tf:"private,omitempty"`

	// (String)
	Readme *string `json:"readme,omitempty" tf:"readme,omitempty"`

	// (Boolean)
	RepoTemplate *bool `json:"repoTemplate,omitempty" tf:"repo_template,omitempty"`

	// (String)
	SSHURL *string `json:"sshUrl,omitempty" tf:"ssh_url,omitempty"`

	// (String)
	Updated *string `json:"updated,omitempty" tf:"updated,omitempty"`

	// (String) The Owner of the repository
	// The Owner of the repository
	Username *string `json:"username,omitempty" tf:"username,omitempty"`

	// (String) A link to a website with more information.
	// A link to a website with more information.
	Website *string `json:"website,omitempty" tf:"website,omitempty"`
}

type RepositoryParameters struct {

	// (Boolean)
	// +kubebuilder:validation:Optional
	AllowManualMerge *bool `json:"allowManualMerge,omitempty" tf:"allow_manual_merge,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	AllowMergeCommits *bool `json:"allowMergeCommits,omitempty" tf:"allow_merge_commits,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	AllowRebase *bool `json:"allowRebase,omitempty" tf:"allow_rebase,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	AllowRebaseExplicit *bool `json:"allowRebaseExplicit,omitempty" tf:"allow_rebase_explicit,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	AllowSquashMerge *bool `json:"allowSquashMerge,omitempty" tf:"allow_squash_merge,omitempty"`

	// (Boolean) Set to 'true' to archive the repository instead of deleting on destroy.
	// Set to 'true' to archive the repository instead of deleting on destroy.
	// +kubebuilder:validation:Optional
	ArchiveOnDestroy *bool `json:"archiveOnDestroy,omitempty" tf:"archive_on_destroy,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	Archived *bool `json:"archived,omitempty" tf:"archived,omitempty"`

	// (Boolean) Flag if the repository should be initiated with the configured values
	// Flag if the repository should be initiated with the configured values
	// +kubebuilder:validation:Optional
	AutoInit *bool `json:"autoInit,omitempty" tf:"auto_init,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	AutodetectManualMerge *bool `json:"autodetectManualMerge,omitempty" tf:"autodetect_manual_merge,omitempty"`

	// (String) The default branch of the repository. Defaults to main
	// The default branch of the repository. Defaults to `main`
	// +kubebuilder:validation:Optional
	DefaultBranch *string `json:"defaultBranch,omitempty" tf:"default_branch,omitempty"`

	// (String) The description of the repository.
	// The description of the repository.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) A specific gitignore that should be commited to the repositoryon creation if auto_init is set to true
	// Need to exist in the gitea instance
	// A specific gitignore that should be commited to the repositoryon creation if `auto_init` is set to `true`
	// Need to exist in the gitea instance
	// +kubebuilder:validation:Optional
	Gitignores *string `json:"gitignores,omitempty" tf:"gitignores,omitempty"`

	// (Boolean) A flag if the repository should have issue management enabled or not.
	// A flag if the repository should have issue management enabled or not.
	// +kubebuilder:validation:Optional
	HasIssues *bool `json:"hasIssues,omitempty" tf:"has_issues,omitempty"`

	// (Boolean) A flag if the repository should have the native project management enabled or not.
	// A flag if the repository should have the native project management enabled or not.
	// +kubebuilder:validation:Optional
	HasProjects *bool `json:"hasProjects,omitempty" tf:"has_projects,omitempty"`

	// (Boolean) A flag if the repository should acceppt pull requests or not.
	// A flag if the repository should acceppt pull requests or not.
	// +kubebuilder:validation:Optional
	HasPullRequests *bool `json:"hasPullRequests,omitempty" tf:"has_pull_requests,omitempty"`

	// (Boolean) A flag if the repository should have the native wiki enabled or not.
	// A flag if the repository should have the native wiki enabled or not.
	// +kubebuilder:validation:Optional
	HasWiki *bool `json:"hasWiki,omitempty" tf:"has_wiki,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	IgnoreWhitespaceConflicts *bool `json:"ignoreWhitespaceConflicts,omitempty" tf:"ignore_whitespace_conflicts,omitempty"`

	// (String) The Issue Label configuration to be used in this repository.
	// Need to exist in the gitea instance
	// The Issue Label configuration to be used in this repository.
	// Need to exist in the gitea instance
	// +kubebuilder:validation:Optional
	IssueLabels *string `json:"issueLabels,omitempty" tf:"issue_labels,omitempty"`

	// (String) The license under which the source code of this repository should be.
	// Need to exist in the gitea instance
	// The license under which the source code of this repository should be.
	// Need to exist in the gitea instance
	// +kubebuilder:validation:Optional
	License *string `json:"license,omitempty" tf:"license,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	MigrationCloneAddress *string `json:"migrationCloneAddress,omitempty" tf:"migration_clone_address,omitempty"`

	// (String) DEPRECATED in favor of migration_clone_address
	// DEPRECATED in favor of `migration_clone_address`
	// +kubebuilder:validation:Optional
	MigrationCloneAddresse *string `json:"migrationCloneAddresse,omitempty" tf:"migration_clone_addresse,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	MigrationIssueLabels *bool `json:"migrationIssueLabels,omitempty" tf:"migration_issue_labels,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	MigrationLfs *bool `json:"migrationLfs,omitempty" tf:"migration_lfs,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	MigrationLfsEndpoint *string `json:"migrationLfsEndpoint,omitempty" tf:"migration_lfs_endpoint,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	MigrationMilestones *bool `json:"migrationMilestones,omitempty" tf:"migration_milestones,omitempty"`

	// (String) valid time units are 'h', 'm', 's'. 0 to disable automatic sync
	// valid time units are 'h', 'm', 's'. 0 to disable automatic sync
	// +kubebuilder:validation:Optional
	MigrationMirrorInterval *string `json:"migrationMirrorInterval,omitempty" tf:"migration_mirror_interval,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	MigrationReleases *bool `json:"migrationReleases,omitempty" tf:"migration_releases,omitempty"`

	// (String) git/github/gitlab/gitea/gogs
	// git/github/gitlab/gitea/gogs
	// +kubebuilder:validation:Optional
	MigrationService *string `json:"migrationService,omitempty" tf:"migration_service,omitempty"`

	// (String, Sensitive)
	// +kubebuilder:validation:Optional
	MigrationServiceAuthPasswordSecretRef *v1.LocalSecretKeySelector `json:"migrationServiceAuthPasswordSecretRef,omitempty" tf:"-"`

	// (String, Sensitive)
	// +kubebuilder:validation:Optional
	MigrationServiceAuthTokenSecretRef *v1.LocalSecretKeySelector `json:"migrationServiceAuthTokenSecretRef,omitempty" tf:"-"`

	// (String)
	// +kubebuilder:validation:Optional
	MigrationServiceAuthUsername *string `json:"migrationServiceAuthUsername,omitempty" tf:"migration_service_auth_username,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	Mirror *bool `json:"mirror,omitempty" tf:"mirror,omitempty"`

	// (String) The Name of the repository
	// The Name of the repository
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Flag if the repository should be private or not.
	// Flag if the repository should be private or not.
	// +kubebuilder:validation:Optional
	Private *bool `json:"private,omitempty" tf:"private,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Readme *string `json:"readme,omitempty" tf:"readme,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	RepoTemplate *bool `json:"repoTemplate,omitempty" tf:"repo_template,omitempty"`

	// (String) The Owner of the repository
	// The Owner of the repository
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`

	// (String) A link to a website with more information.
	// A link to a website with more information.
	// +kubebuilder:validation:Optional
	Website *string `json:"website,omitempty" tf:"website,omitempty"`
}

// RepositorySpec defines the desired state of Repository
type RepositorySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            RepositoryParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RepositoryInitParameters `json:"initProvider,omitempty"`
}

// RepositoryStatus defines the observed state of Repository.
type RepositoryStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RepositoryObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Repository is the Schema for the Repositorys API. gitea_repository manages a gitea repository. Per default this repository will be initializiled with the provided configuration (gitignore, License etc.). If the username property is set to a organisation name, the provider will try to look if this organisation exists and create the repository under the organisation scope. Repository migrations have some properties that are not available to regular repositories. These are all prefixed with migration_.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gitea}
type Repository struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.username) || (has(self.initProvider) && has(self.initProvider.username))",message="spec.forProvider.username is a required parameter"
	Spec   RepositorySpec   `json:"spec"`
	Status RepositoryStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RepositoryList contains a list of Repositorys
type RepositoryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Repository `json:"items"`
}

// Repository type metadata.
var (
	Repository_Kind             = "Repository"
	Repository_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Repository_Kind}.String()
	Repository_KindAPIVersion   = Repository_Kind + "." + CRDGroupVersion.String()
	Repository_GroupVersionKind = CRDGroupVersion.WithKind(Repository_Kind)
)

func init() {
	SchemeBuilder.Register(&Repository{}, &RepositoryList{})
}
