// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type TeamInitParameters struct {

	// (Boolean) Flag if the Teams members should be able to create Rpositories in the Organisation
	// Flag if the Teams members should be able to create Rpositories in the Organisation
	CanCreateRepos *bool `json:"canCreateRepos,omitempty" tf:"can_create_repos,omitempty"`

	// (String) Description of the Team
	// Description of the Team
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Flag if the Teams members should have access to all Repositories in the Organisation
	// Flag if the Teams members should have access to all Repositories in the Organisation
	IncludeAllRepositories *bool `json:"includeAllRepositories,omitempty" tf:"include_all_repositories,omitempty"`

	// (String) Name of the Team
	// Name of the Team
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The organisation which this Team is part of.
	// The organisation which this Team is part of.
	Organisation *string `json:"organisation,omitempty" tf:"organisation,omitempty"`

	// (String) Permissions associated with this Team
	// Can be none, read, write, admin or owner
	// Permissions associated with this Team
	// Can be `none`, `read`, `write`, `admin` or `owner`
	Permission *string `json:"permission,omitempty" tf:"permission,omitempty"`

	// (List of String) List of Repositories that should be part of this team
	// List of Repositories that should be part of this team
	Repositories []*string `json:"repositories,omitempty" tf:"repositories,omitempty"`

	// (String) List of types of Repositories that should be allowed to be created from Team members.
	// Can be repo.code, repo.issues, repo.ext_issues, repo.wiki, repo.pulls, repo.releases, repo.projects and/or repo.ext_wiki
	// List of types of Repositories that should be allowed to be created from Team members.
	// Can be `repo.code`, `repo.issues`, `repo.ext_issues`, `repo.wiki`, `repo.pulls`, `repo.releases`, `repo.projects` and/or `repo.ext_wiki`
	Units *string `json:"units,omitempty" tf:"units,omitempty"`
}

type TeamObservation struct {

	// (Boolean) Flag if the Teams members should be able to create Rpositories in the Organisation
	// Flag if the Teams members should be able to create Rpositories in the Organisation
	CanCreateRepos *bool `json:"canCreateRepos,omitempty" tf:"can_create_repos,omitempty"`

	// (String) Description of the Team
	// Description of the Team
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Flag if the Teams members should have access to all Repositories in the Organisation
	// Flag if the Teams members should have access to all Repositories in the Organisation
	IncludeAllRepositories *bool `json:"includeAllRepositories,omitempty" tf:"include_all_repositories,omitempty"`

	// (String) Name of the Team
	// Name of the Team
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The organisation which this Team is part of.
	// The organisation which this Team is part of.
	Organisation *string `json:"organisation,omitempty" tf:"organisation,omitempty"`

	// (String) Permissions associated with this Team
	// Can be none, read, write, admin or owner
	// Permissions associated with this Team
	// Can be `none`, `read`, `write`, `admin` or `owner`
	Permission *string `json:"permission,omitempty" tf:"permission,omitempty"`

	// (List of String) List of Repositories that should be part of this team
	// List of Repositories that should be part of this team
	Repositories []*string `json:"repositories,omitempty" tf:"repositories,omitempty"`

	// (String) List of types of Repositories that should be allowed to be created from Team members.
	// Can be repo.code, repo.issues, repo.ext_issues, repo.wiki, repo.pulls, repo.releases, repo.projects and/or repo.ext_wiki
	// List of types of Repositories that should be allowed to be created from Team members.
	// Can be `repo.code`, `repo.issues`, `repo.ext_issues`, `repo.wiki`, `repo.pulls`, `repo.releases`, `repo.projects` and/or `repo.ext_wiki`
	Units *string `json:"units,omitempty" tf:"units,omitempty"`
}

type TeamParameters struct {

	// (Boolean) Flag if the Teams members should be able to create Rpositories in the Organisation
	// Flag if the Teams members should be able to create Rpositories in the Organisation
	// +kubebuilder:validation:Optional
	CanCreateRepos *bool `json:"canCreateRepos,omitempty" tf:"can_create_repos,omitempty"`

	// (String) Description of the Team
	// Description of the Team
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Flag if the Teams members should have access to all Repositories in the Organisation
	// Flag if the Teams members should have access to all Repositories in the Organisation
	// +kubebuilder:validation:Optional
	IncludeAllRepositories *bool `json:"includeAllRepositories,omitempty" tf:"include_all_repositories,omitempty"`

	// (String) Name of the Team
	// Name of the Team
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The organisation which this Team is part of.
	// The organisation which this Team is part of.
	// +kubebuilder:validation:Optional
	Organisation *string `json:"organisation,omitempty" tf:"organisation,omitempty"`

	// (String) Permissions associated with this Team
	// Can be none, read, write, admin or owner
	// Permissions associated with this Team
	// Can be `none`, `read`, `write`, `admin` or `owner`
	// +kubebuilder:validation:Optional
	Permission *string `json:"permission,omitempty" tf:"permission,omitempty"`

	// (List of String) List of Repositories that should be part of this team
	// List of Repositories that should be part of this team
	// +kubebuilder:validation:Optional
	Repositories []*string `json:"repositories,omitempty" tf:"repositories,omitempty"`

	// (String) List of types of Repositories that should be allowed to be created from Team members.
	// Can be repo.code, repo.issues, repo.ext_issues, repo.wiki, repo.pulls, repo.releases, repo.projects and/or repo.ext_wiki
	// List of types of Repositories that should be allowed to be created from Team members.
	// Can be `repo.code`, `repo.issues`, `repo.ext_issues`, `repo.wiki`, `repo.pulls`, `repo.releases`, `repo.projects` and/or `repo.ext_wiki`
	// +kubebuilder:validation:Optional
	Units *string `json:"units,omitempty" tf:"units,omitempty"`
}

// TeamSpec defines the desired state of Team
type TeamSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            TeamParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TeamInitParameters `json:"initProvider,omitempty"`
}

// TeamStatus defines the observed state of Team.
type TeamStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TeamObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Team is the Schema for the Teams API. gitea_team manages Team that are part of an organisation.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gitea}
type Team struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.organisation) || (has(self.initProvider) && has(self.initProvider.organisation))",message="spec.forProvider.organisation is a required parameter"
	Spec   TeamSpec   `json:"spec"`
	Status TeamStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TeamList contains a list of Teams
type TeamList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Team `json:"items"`
}

// Repository type metadata.
var (
	Team_Kind             = "Team"
	Team_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Team_Kind}.String()
	Team_KindAPIVersion   = Team_Kind + "." + CRDGroupVersion.String()
	Team_GroupVersionKind = CRDGroupVersion.WithKind(Team_Kind)
)

func init() {
	SchemeBuilder.Register(&Team{}, &TeamList{})
}
