// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type UserInitParameters struct {

	// (Boolean) Flag if this user should be active or not
	// Flag if this user should be active or not
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// (Boolean) Flag if this user should be an administrator or not
	// Flag if this user should be an administrator or not
	Admin *bool `json:"admin,omitempty" tf:"admin,omitempty"`

	// (Boolean)
	AllowCreateOrganization *bool `json:"allowCreateOrganization,omitempty" tf:"allow_create_organization,omitempty"`

	// (Boolean)
	AllowGitHook *bool `json:"allowGitHook,omitempty" tf:"allow_git_hook,omitempty"`

	// (Boolean)
	AllowImportLocal *bool `json:"allowImportLocal,omitempty" tf:"allow_import_local,omitempty"`

	// (String) A description of the user
	// A description of the user
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Mail Address of the user
	// E-Mail Address of the user
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (Boolean) Flag if the user defined password should be overwritten or not
	// Flag if the user defined password should be overwritten or not
	ForcePasswordChange *bool `json:"forcePasswordChange,omitempty" tf:"force_password_change,omitempty"`

	// (String) Full name of the user
	// Full name of the user
	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	// (String)
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) The login name can differ from the username
	// The login name can differ from the username
	LoginName *string `json:"loginName,omitempty" tf:"login_name,omitempty"`

	// (Number)
	MaxRepoCreation *float64 `json:"maxRepoCreation,omitempty" tf:"max_repo_creation,omitempty"`

	// (Boolean) Flag if the user should change the password after first login
	// Flag if the user should change the password after first login
	MustChangePassword *bool `json:"mustChangePassword,omitempty" tf:"must_change_password,omitempty"`

	// (String, Sensitive) Password to be set for the user
	// Password to be set for the user
	PasswordSecretRef v1.LocalSecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// (Boolean) Flag if the user should not be allowed to log in (bot user)
	// Flag if the user should not be allowed to log in (bot user)
	ProhibitLogin *bool `json:"prohibitLogin,omitempty" tf:"prohibit_login,omitempty"`

	// (Boolean)
	Restricted *bool `json:"restricted,omitempty" tf:"restricted,omitempty"`

	// (Boolean) Flag to send a notification about the user creation to the defined email
	// Flag to send a notification about the user creation to the defined `email`
	SendNotification *bool `json:"sendNotification,omitempty" tf:"send_notification,omitempty"`

	// (String) Username of the user to be created
	// Username of the user to be created
	Username *string `json:"username,omitempty" tf:"username,omitempty"`

	// (String) Visibility of the user. Can be public, limited or private
	// Visibility of the user. Can be `public`, `limited` or `private`
	Visibility *string `json:"visibility,omitempty" tf:"visibility,omitempty"`
}

type UserObservation struct {

	// (Boolean) Flag if this user should be active or not
	// Flag if this user should be active or not
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// (Boolean) Flag if this user should be an administrator or not
	// Flag if this user should be an administrator or not
	Admin *bool `json:"admin,omitempty" tf:"admin,omitempty"`

	// (Boolean)
	AllowCreateOrganization *bool `json:"allowCreateOrganization,omitempty" tf:"allow_create_organization,omitempty"`

	// (Boolean)
	AllowGitHook *bool `json:"allowGitHook,omitempty" tf:"allow_git_hook,omitempty"`

	// (Boolean)
	AllowImportLocal *bool `json:"allowImportLocal,omitempty" tf:"allow_import_local,omitempty"`

	// (String) A description of the user
	// A description of the user
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Mail Address of the user
	// E-Mail Address of the user
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (Boolean) Flag if the user defined password should be overwritten or not
	// Flag if the user defined password should be overwritten or not
	ForcePasswordChange *bool `json:"forcePasswordChange,omitempty" tf:"force_password_change,omitempty"`

	// (String) Full name of the user
	// Full name of the user
	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) The login name can differ from the username
	// The login name can differ from the username
	LoginName *string `json:"loginName,omitempty" tf:"login_name,omitempty"`

	// (Number)
	MaxRepoCreation *float64 `json:"maxRepoCreation,omitempty" tf:"max_repo_creation,omitempty"`

	// (Boolean) Flag if the user should change the password after first login
	// Flag if the user should change the password after first login
	MustChangePassword *bool `json:"mustChangePassword,omitempty" tf:"must_change_password,omitempty"`

	// (Boolean) Flag if the user should not be allowed to log in (bot user)
	// Flag if the user should not be allowed to log in (bot user)
	ProhibitLogin *bool `json:"prohibitLogin,omitempty" tf:"prohibit_login,omitempty"`

	// (Boolean)
	Restricted *bool `json:"restricted,omitempty" tf:"restricted,omitempty"`

	// (Boolean) Flag to send a notification about the user creation to the defined email
	// Flag to send a notification about the user creation to the defined `email`
	SendNotification *bool `json:"sendNotification,omitempty" tf:"send_notification,omitempty"`

	// (String) Username of the user to be created
	// Username of the user to be created
	Username *string `json:"username,omitempty" tf:"username,omitempty"`

	// (String) Visibility of the user. Can be public, limited or private
	// Visibility of the user. Can be `public`, `limited` or `private`
	Visibility *string `json:"visibility,omitempty" tf:"visibility,omitempty"`
}

type UserParameters struct {

	// (Boolean) Flag if this user should be active or not
	// Flag if this user should be active or not
	// +kubebuilder:validation:Optional
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// (Boolean) Flag if this user should be an administrator or not
	// Flag if this user should be an administrator or not
	// +kubebuilder:validation:Optional
	Admin *bool `json:"admin,omitempty" tf:"admin,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	AllowCreateOrganization *bool `json:"allowCreateOrganization,omitempty" tf:"allow_create_organization,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	AllowGitHook *bool `json:"allowGitHook,omitempty" tf:"allow_git_hook,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	AllowImportLocal *bool `json:"allowImportLocal,omitempty" tf:"allow_import_local,omitempty"`

	// (String) A description of the user
	// A description of the user
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Mail Address of the user
	// E-Mail Address of the user
	// +kubebuilder:validation:Optional
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (Boolean) Flag if the user defined password should be overwritten or not
	// Flag if the user defined password should be overwritten or not
	// +kubebuilder:validation:Optional
	ForcePasswordChange *bool `json:"forcePasswordChange,omitempty" tf:"force_password_change,omitempty"`

	// (String) Full name of the user
	// Full name of the user
	// +kubebuilder:validation:Optional
	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) The login name can differ from the username
	// The login name can differ from the username
	// +kubebuilder:validation:Optional
	LoginName *string `json:"loginName,omitempty" tf:"login_name,omitempty"`

	// (Number)
	// +kubebuilder:validation:Optional
	MaxRepoCreation *float64 `json:"maxRepoCreation,omitempty" tf:"max_repo_creation,omitempty"`

	// (Boolean) Flag if the user should change the password after first login
	// Flag if the user should change the password after first login
	// +kubebuilder:validation:Optional
	MustChangePassword *bool `json:"mustChangePassword,omitempty" tf:"must_change_password,omitempty"`

	// (String, Sensitive) Password to be set for the user
	// Password to be set for the user
	// +kubebuilder:validation:Optional
	PasswordSecretRef v1.LocalSecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// (Boolean) Flag if the user should not be allowed to log in (bot user)
	// Flag if the user should not be allowed to log in (bot user)
	// +kubebuilder:validation:Optional
	ProhibitLogin *bool `json:"prohibitLogin,omitempty" tf:"prohibit_login,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	Restricted *bool `json:"restricted,omitempty" tf:"restricted,omitempty"`

	// (Boolean) Flag to send a notification about the user creation to the defined email
	// Flag to send a notification about the user creation to the defined `email`
	// +kubebuilder:validation:Optional
	SendNotification *bool `json:"sendNotification,omitempty" tf:"send_notification,omitempty"`

	// (String) Username of the user to be created
	// Username of the user to be created
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`

	// (String) Visibility of the user. Can be public, limited or private
	// Visibility of the user. Can be `public`, `limited` or `private`
	// +kubebuilder:validation:Optional
	Visibility *string `json:"visibility,omitempty" tf:"visibility,omitempty"`
}

// UserSpec defines the desired state of User
type UserSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            UserParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserInitParameters `json:"initProvider,omitempty"`
}

// UserStatus defines the observed state of User.
type UserStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        UserObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// User is the Schema for the Users API. gitea_user manages a native gitea user. If you are using OIDC or other kinds of authentication mechanisms you can still try to managessh keys or other ressources this way
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gitea}
type User struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.email) || (has(self.initProvider) && has(self.initProvider.email))",message="spec.forProvider.email is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.loginName) || (has(self.initProvider) && has(self.initProvider.loginName))",message="spec.forProvider.loginName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.passwordSecretRef)",message="spec.forProvider.passwordSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.username) || (has(self.initProvider) && has(self.initProvider.username))",message="spec.forProvider.username is a required parameter"
	Spec   UserSpec   `json:"spec"`
	Status UserStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserList contains a list of Users
type UserList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []User `json:"items"`
}

// Repository type metadata.
var (
	User_Kind             = "User"
	User_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: User_Kind}.String()
	User_KindAPIVersion   = User_Kind + "." + CRDGroupVersion.String()
	User_GroupVersionKind = CRDGroupVersion.WithKind(User_Kind)
)

func init() {
	SchemeBuilder.Register(&User{}, &UserList{})
}
