// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AppInitParameters struct {

	// If set to false, it will be a public client (PKCE will be required)
	ConfidentialClient *bool `json:"confidentialClient,omitempty" tf:"confidential_client,omitempty"`

	// OAuth Application name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Accepted redirect URIs
	// +listType=set
	RedirectUris []*string `json:"redirectUris,omitempty" tf:"redirect_uris,omitempty"`
}

type AppObservation struct {

	// OAuth2 Application client id
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// If set to false, it will be a public client (PKCE will be required)
	ConfidentialClient *bool `json:"confidentialClient,omitempty" tf:"confidential_client,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// OAuth Application name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Accepted redirect URIs
	// +listType=set
	RedirectUris []*string `json:"redirectUris,omitempty" tf:"redirect_uris,omitempty"`
}

type AppParameters struct {

	// If set to false, it will be a public client (PKCE will be required)
	// +kubebuilder:validation:Optional
	ConfidentialClient *bool `json:"confidentialClient,omitempty" tf:"confidential_client,omitempty"`

	// OAuth Application name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Accepted redirect URIs
	// +kubebuilder:validation:Optional
	// +listType=set
	RedirectUris []*string `json:"redirectUris,omitempty" tf:"redirect_uris,omitempty"`
}

// AppSpec defines the desired state of App
type AppSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            AppParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AppInitParameters `json:"initProvider,omitempty"`
}

// AppStatus defines the observed state of App.
type AppStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AppObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// App is the Schema for the Apps API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gitea}
type App struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.redirectUris) || (has(self.initProvider) && has(self.initProvider.redirectUris))",message="spec.forProvider.redirectUris is a required parameter"
	Spec   AppSpec   `json:"spec"`
	Status AppStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AppList contains a list of Apps
type AppList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []App `json:"items"`
}

// Repository type metadata.
var (
	App_Kind             = "App"
	App_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: App_Kind}.String()
	App_KindAPIVersion   = App_Kind + "." + CRDGroupVersion.String()
	App_GroupVersionKind = CRDGroupVersion.WithKind(App_Kind)
)

func init() {
	SchemeBuilder.Register(&App{}, &AppList{})
}
