// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type HookInitParameters struct {

	// (String) Content of the git hook
	// Content of the git hook
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// (String) Name of the git hook to configure
	// Name of the git hook to configure
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The repository that this hook belongs too.
	// The repository that this hook belongs too.
	Repo *string `json:"repo,omitempty" tf:"repo,omitempty"`

	// (String) The user (or organisation) owning the repo this hook belongs too
	// The user (or organisation) owning the repo this hook belongs too
	User *string `json:"user,omitempty" tf:"user,omitempty"`
}

type HookObservation struct {

	// (String) Content of the git hook
	// Content of the git hook
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Name of the git hook to configure
	// Name of the git hook to configure
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The repository that this hook belongs too.
	// The repository that this hook belongs too.
	Repo *string `json:"repo,omitempty" tf:"repo,omitempty"`

	// (String) The user (or organisation) owning the repo this hook belongs too
	// The user (or organisation) owning the repo this hook belongs too
	User *string `json:"user,omitempty" tf:"user,omitempty"`
}

type HookParameters struct {

	// (String) Content of the git hook
	// Content of the git hook
	// +kubebuilder:validation:Optional
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// (String) Name of the git hook to configure
	// Name of the git hook to configure
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The repository that this hook belongs too.
	// The repository that this hook belongs too.
	// +kubebuilder:validation:Optional
	Repo *string `json:"repo,omitempty" tf:"repo,omitempty"`

	// (String) The user (or organisation) owning the repo this hook belongs too
	// The user (or organisation) owning the repo this hook belongs too
	// +kubebuilder:validation:Optional
	User *string `json:"user,omitempty" tf:"user,omitempty"`
}

// HookSpec defines the desired state of Hook
type HookSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            HookParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider HookInitParameters `json:"initProvider,omitempty"`
}

// HookStatus defines the observed state of Hook.
type HookStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        HookObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Hook is the Schema for the Hooks API. gitea_git_hook manages git hooks on a repository. import is currently not supported WARNING: using this resource requires to enable server side hookswhich are known to cause security issues https://github.com/go-gitea/gitea/pull/13058! if you want to procede, you need to enable server side hooks as stated here https://docs.gitea.io/en-us/config-cheat-sheet/#security-security
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gitea}
type Hook struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.content) || (has(self.initProvider) && has(self.initProvider.content))",message="spec.forProvider.content is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.repo) || (has(self.initProvider) && has(self.initProvider.repo))",message="spec.forProvider.repo is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.user) || (has(self.initProvider) && has(self.initProvider.user))",message="spec.forProvider.user is a required parameter"
	Spec   HookSpec   `json:"spec"`
	Status HookStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// HookList contains a list of Hooks
type HookList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Hook `json:"items"`
}

// Repository type metadata.
var (
	Hook_Kind             = "Hook"
	Hook_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Hook_Kind}.String()
	Hook_KindAPIVersion   = Hook_Kind + "." + CRDGroupVersion.String()
	Hook_GroupVersionKind = CRDGroupVersion.WithKind(Hook_Kind)
)

func init() {
	SchemeBuilder.Register(&Hook{}, &HookList{})
}
